package dev.itsmeow.betteranimalsplus.client.model;

import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;

import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * squid_giant - Batman, Cybercat5555
 * Created using Tabula 8.0.0
 */
public class ModelGiantSquid<T extends Entity> extends EntityModel<T> {
    public ModelRenderer head;
    public ModelRenderer mantle;
    public ModelRenderer lEye;
    public ModelRenderer rEye;
    public ModelRenderer tentacleLongL0;
    public ModelRenderer tentacleLT0;
    public ModelRenderer tentacleRT0;
    public ModelRenderer tentacleT0;
    public ModelRenderer tentacleRM0;
    public ModelRenderer tentacleRB0;
    public ModelRenderer tentacleLM0;
    public ModelRenderer tentacleLB0;
    public ModelRenderer tentacleB0;
    public ModelRenderer tentacleLongR0;
    public ModelRenderer siphon;
    public ModelRenderer beakTop;
    public ModelRenderer beakLow;
    public ModelRenderer mantleBack;
    public ModelRenderer mantleTop;
    public ModelRenderer mantleTipTop;
    public ModelRenderer mantleTipLow;
    public ModelRenderer fin0;
    public ModelRenderer fin1;
    public ModelRenderer tentacleLongL1;
    public ModelRenderer tentacleLongL2;
    public ModelRenderer tentacleLongL3;
    public ModelRenderer tentacleLongL4;
    public ModelRenderer tentacleLongL5;
    public ModelRenderer tentacleLongL6;
    public ModelRenderer tentacleLongL7;
    public ModelRenderer tentacleLongLHand;
    public ModelRenderer tentacleLT1;
    public ModelRenderer tentacleLT2;
    public ModelRenderer tentacleLT3;
    public ModelRenderer tentacleLT4;
    public ModelRenderer tentacleRT1;
    public ModelRenderer tentacleRT2;
    public ModelRenderer tentacleRT3;
    public ModelRenderer tentacleRT4;
    public ModelRenderer tentacleT1;
    public ModelRenderer tentacleT2;
    public ModelRenderer tentacleT3;
    public ModelRenderer tentacleT4;
    public ModelRenderer tentacleRM1;
    public ModelRenderer tentacleRM2;
    public ModelRenderer tentacleRM3;
    public ModelRenderer tentacleRM4;
    public ModelRenderer tentacleRB1;
    public ModelRenderer tentacleRB2;
    public ModelRenderer tentacleRB3;
    public ModelRenderer tentacleRB4;
    public ModelRenderer tentacleLM1;
    public ModelRenderer tentacleLM2;
    public ModelRenderer tentacleLM3;
    public ModelRenderer tentacleLM4;
    public ModelRenderer tentacleLB1;
    public ModelRenderer tentacleLB2;
    public ModelRenderer tentacleLB3;
    public ModelRenderer tentacleLB4;
    public ModelRenderer tentacleB1;
    public ModelRenderer tentacleB2;
    public ModelRenderer tentacleB3;
    public ModelRenderer tentacleB4;
    public ModelRenderer tentacleLongR1;
    public ModelRenderer tentacleLongR2;
    public ModelRenderer tentacleLongR3;
    public ModelRenderer tentacleLongR4;
    public ModelRenderer tentacleLongR5;
    public ModelRenderer tentacleLongR6;
    public ModelRenderer tentacleLongR7;
    public ModelRenderer tentacleLongRHand;
    protected ModelRenderer[] mainTentacles;

    public ModelGiantSquid() {
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.tentacleLongL5 = new ModelRenderer(this, 27, 0);
        this.tentacleLongL5.mirror = true;
        this.tentacleLongL5.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongL5.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRM2 = new ModelRenderer(this, 46, 0);
        this.tentacleRM2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRM2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLB3 = new ModelRenderer(this, 46, 0);
        this.tentacleLB3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLB3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRT3 = new ModelRenderer(this, 46, 0);
        this.tentacleRT3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRT3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongR6 = new ModelRenderer(this, 27, 0);
        this.tentacleLongR6.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongR6.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleLongR6, 0.0F, -0.136659280431156F, 0.0F);
        this.mantleBack = new ModelRenderer(this, 0, 34);
        this.mantleBack.setRotationPoint(0.0F, 1.1F, 10.0F);
        this.mantleBack.addBox(-3.0F, -1.0F, 0.0F, 6, 4, 12, 0.0F);
        this.setRotateAngle(mantleBack, 0.136659280431156F, 0.0F, 0.0F);
        this.tentacleLongLHand = new ModelRenderer(this, 35, 24);
        this.tentacleLongLHand.mirror = true;
        this.tentacleLongLHand.setRotationPoint(0.0F, 0.0F, -6.5F);
        this.tentacleLongLHand.addBox(-1.0F, -1.5F, -10.0F, 2, 3, 10, 0.0F);
        this.setRotateAngle(tentacleLongLHand, 0.0F, 0.22759093446006054F, 0.0F);
        this.tentacleB0 = new ModelRenderer(this, 46, 0);
        this.tentacleB0.setRotationPoint(0.0F, 2.5F, -6.7F);
        this.tentacleB0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleB0, -0.03490658503988659F, 0.0F, -3.141592653589793F);
        this.tentacleRB0 = new ModelRenderer(this, 46, 0);
        this.tentacleRB0.setRotationPoint(-2.3F, 2.5F, -6.7F);
        this.tentacleRB0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleRB0, 0.0F, 0.0F, -2.2689280275926285F);
        this.tentacleRB3 = new ModelRenderer(this, 46, 0);
        this.tentacleRB3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRB3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.mantleTop = new ModelRenderer(this, 0, 19);
        this.mantleTop.setRotationPoint(0.0F, -4.5F, 1.5F);
        this.mantleTop.addBox(-3.5F, 0.0F, 0.0F, 7, 4, 11, 0.0F);
        this.setRotateAngle(mantleTop, -0.31869712141416456F, 0.0F, 0.0F);
        this.beakLow = new ModelRenderer(this, 0, 5);
        this.beakLow.setRotationPoint(0.0F, 2.0F, -8.8F);
        this.beakLow.addBox(-1.5F, -2.0F, -2.0F, 3, 2, 2, 0.0F);
        this.setRotateAngle(beakLow, -0.136659280431156F, 0.0F, 0.0F);
        this.tentacleLB1 = new ModelRenderer(this, 46, 0);
        this.tentacleLB1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLB1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLB0 = new ModelRenderer(this, 46, 0);
        this.tentacleLB0.setRotationPoint(2.3F, 2.5F, -6.7F);
        this.tentacleLB0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleLB0, 0.0F, 0.0F, 2.2689280275926285F);
        this.tentacleLongL2 = new ModelRenderer(this, 39, 10);
        this.tentacleLongL2.mirror = true;
        this.tentacleLongL2.setRotationPoint(0.0F, 0.0F, -9.7F);
        this.tentacleLongL2.addBox(-1.0F, -1.0F, -10.0F, 2, 2, 10, 0.0F);
        this.tentacleLongR0 = new ModelRenderer(this, 39, 10);
        this.tentacleLongR0.setRotationPoint(-2.5F, -1.0F, -6.4F);
        this.tentacleLongR0.addBox(-1.0F, -1.0F, -10.0F, 2, 2, 10, 0.0F);
        this.setRotateAngle(tentacleLongR0, 0.0F, 0.27314402793711257F, 0.0F);
        this.tentacleLongL0 = new ModelRenderer(this, 39, 10);
        this.tentacleLongL0.mirror = true;
        this.tentacleLongL0.setRotationPoint(2.5F, -1.0F, -6.4F);
        this.tentacleLongL0.addBox(-1.0F, -1.0F, -10.0F, 2, 2, 10, 0.0F);
        this.setRotateAngle(tentacleLongL0, 0.0F, -0.27314402793711257F, 0.0F);
        this.tentacleLT3 = new ModelRenderer(this, 46, 0);
        this.tentacleLT3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLT3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRM3 = new ModelRenderer(this, 46, 0);
        this.tentacleRM3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRM3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLB4 = new ModelRenderer(this, 46, 0);
        this.tentacleLB4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLB4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.mantleTipLow = new ModelRenderer(this, 21, 50);
        this.mantleTipLow.setRotationPoint(0.0F, 2.0F, 0.3F);
        this.mantleTipLow.addBox(-2.0F, 0.0F, 0.0F, 4, 2, 5, 0.0F);
        this.setRotateAngle(mantleTipLow, 0.36425021489121656F, 0.0F, 0.0F);
        this.tentacleLongR1 = new ModelRenderer(this, 39, 10);
        this.tentacleLongR1.setRotationPoint(0.0F, 0.0F, -9.7F);
        this.tentacleLongR1.addBox(-1.0F, -1.0F, -10.0F, 2, 2, 10, 0.0F);
        this.tentacleLM3 = new ModelRenderer(this, 46, 0);
        this.tentacleLM3.mirror = true;
        this.tentacleLM3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLM3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.siphon = new ModelRenderer(this, 0, 22);
        this.siphon.setRotationPoint(0.0F, 3.3F, -0.7F);
        this.siphon.addBox(-0.5F, -0.5F, -4.0F, 1, 1, 4, 0.0F);
        this.setRotateAngle(siphon, 0.40980330836826856F, 0.0F, 0.0F);
        this.tentacleLongR4 = new ModelRenderer(this, 27, 0);
        this.tentacleLongR4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongR4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.mantleTipTop = new ModelRenderer(this, 25, 22);
        this.mantleTipTop.setRotationPoint(0.0F, 0.0F, 11.0F);
        this.mantleTipTop.addBox(-2.5F, 0.0F, 0.0F, 5, 2, 5, 0.0F);
        this.tentacleLongR2 = new ModelRenderer(this, 39, 10);
        this.tentacleLongR2.setRotationPoint(0.0F, 0.0F, -9.7F);
        this.tentacleLongR2.addBox(-1.0F, -1.0F, -10.0F, 2, 2, 10, 0.0F);
        this.tentacleB4 = new ModelRenderer(this, 46, 0);
        this.tentacleB4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleB4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.beakTop = new ModelRenderer(this, 0, 0);
        this.beakTop.setRotationPoint(0.0F, -2.0F, -9.0F);
        this.beakTop.addBox(-1.5F, 0.0F, -2.0F, 3, 2, 2, 0.0F);
        this.setRotateAngle(beakTop, 0.136659280431156F, 0.0F, 0.0F);
        this.lEye = new ModelRenderer(this, 0, 34);
        this.lEye.mirror = true;
        this.lEye.setRotationPoint(3.0F, 0.0F, -4.0F);
        this.lEye.addBox(0.0F, -1.5F, -1.5F, 1, 3, 3, 0.0F);
        this.tentacleT2 = new ModelRenderer(this, 46, 0);
        this.tentacleT2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleT2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRM0 = new ModelRenderer(this, 46, 0);
        this.tentacleRM0.setRotationPoint(-2.3F, 0.2F, -6.7F);
        this.tentacleRM0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleRM0, 0.0F, 0.0F, -1.5707963267948966F);
        this.tentacleRT4 = new ModelRenderer(this, 46, 0);
        this.tentacleRT4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRT4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRT1 = new ModelRenderer(this, 46, 0);
        this.tentacleRT1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRT1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRM1 = new ModelRenderer(this, 46, 0);
        this.tentacleRM1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRM1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongR5 = new ModelRenderer(this, 27, 0);
        this.tentacleLongR5.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongR5.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLT2 = new ModelRenderer(this, 46, 0);
        this.tentacleLT2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLT2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleT3 = new ModelRenderer(this, 46, 0);
        this.tentacleT3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleT3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRB1 = new ModelRenderer(this, 46, 0);
        this.tentacleRB1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRB1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLB2 = new ModelRenderer(this, 46, 0);
        this.tentacleLB2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLB2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLM2 = new ModelRenderer(this, 46, 0);
        this.tentacleLM2.mirror = true;
        this.tentacleLM2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLM2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.fin0 = new ModelRenderer(this, 32, 37);
        this.fin0.setRotationPoint(0.0F, 1.0F, 1.0F);
        this.fin0.addBox(-4.5F, 0.0F, 0.0F, 9, 1, 7, 0.0F);
        this.tentacleLongL6 = new ModelRenderer(this, 27, 0);
        this.tentacleLongL6.mirror = true;
        this.tentacleLongL6.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongL6.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleLongL6, 0.0F, 0.136659280431156F, 0.0F);
        this.tentacleB1 = new ModelRenderer(this, 46, 0);
        this.tentacleB1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleB1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongRHand = new ModelRenderer(this, 35, 24);
        this.tentacleLongRHand.setRotationPoint(0.0F, 0.0F, -6.5F);
        this.tentacleLongRHand.addBox(-1.0F, -1.5F, -10.0F, 2, 3, 10, 0.0F);
        this.setRotateAngle(tentacleLongRHand, 0.0F, -0.22759093446006054F, 0.0F);
        this.tentacleLongL4 = new ModelRenderer(this, 27, 0);
        this.tentacleLongL4.mirror = true;
        this.tentacleLongL4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongL4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLM1 = new ModelRenderer(this, 46, 0);
        this.tentacleLM1.mirror = true;
        this.tentacleLM1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLM1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.head = new ModelRenderer(this, 35, 50);
        this.head.setRotationPoint(0.0F, 15.0F, 3.0F);
        this.head.addBox(-3.5F, -3.5F, -7.0F, 7, 7, 7, 0.0F);
        this.tentacleT4 = new ModelRenderer(this, 46, 0);
        this.tentacleT4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleT4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRM4 = new ModelRenderer(this, 46, 0);
        this.tentacleRM4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRM4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRB2 = new ModelRenderer(this, 46, 0);
        this.tentacleRB2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRB2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.rEye = new ModelRenderer(this, 0, 34);
        this.rEye.setRotationPoint(-3.0F, 0.0F, -4.0F);
        this.rEye.addBox(-1.0F, -1.5F, -1.5F, 1, 3, 3, 0.0F);
        this.tentacleRT0 = new ModelRenderer(this, 46, 0);
        this.tentacleRT0.setRotationPoint(-2.3F, -2.2F, -6.7F);
        this.tentacleRT0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleRT0, 0.0F, 0.0F, -0.31869712141416456F);
        this.tentacleT1 = new ModelRenderer(this, 46, 0);
        this.tentacleT1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleT1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongL7 = new ModelRenderer(this, 27, 0);
        this.tentacleLongL7.mirror = true;
        this.tentacleLongL7.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongL7.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRT2 = new ModelRenderer(this, 46, 0);
        this.tentacleRT2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRT2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongL1 = new ModelRenderer(this, 39, 10);
        this.tentacleLongL1.mirror = true;
        this.tentacleLongL1.setRotationPoint(0.0F, 0.0F, -9.7F);
        this.tentacleLongL1.addBox(-1.0F, -1.0F, -10.0F, 2, 2, 10, 0.0F);
        this.tentacleB2 = new ModelRenderer(this, 46, 0);
        this.tentacleB2.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleB2.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLM4 = new ModelRenderer(this, 46, 0);
        this.tentacleLM4.mirror = true;
        this.tentacleLM4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLM4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleRB4 = new ModelRenderer(this, 46, 0);
        this.tentacleRB4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleRB4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongR7 = new ModelRenderer(this, 27, 0);
        this.tentacleLongR7.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLongR7.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongL3 = new ModelRenderer(this, 27, 0);
        this.tentacleLongL3.mirror = true;
        this.tentacleLongL3.setRotationPoint(0.0F, 0.0F, -9.7F);
        this.tentacleLongL3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleLongL3, 0.0F, 0.22759093446006054F, 0.0F);
        this.tentacleLT0 = new ModelRenderer(this, 46, 0);
        this.tentacleLT0.setRotationPoint(2.3F, -2.2F, -6.7F);
        this.tentacleLT0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleLT0, 0.0F, 0.0F, 0.31869712141416456F);
        this.tentacleB3 = new ModelRenderer(this, 46, 0);
        this.tentacleB3.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleB3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.fin1 = new ModelRenderer(this, 0, 56);
        this.fin1.setRotationPoint(0.0F, 0.1F, 2.0F);
        this.fin1.addBox(0.0F, 0.0F, 0.0F, 7, 1, 7, 0.0F);
        this.setRotateAngle(fin1, 0.0F, -0.7853981633974483F, 0.0F);
        this.tentacleLT1 = new ModelRenderer(this, 46, 0);
        this.tentacleLT1.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLT1.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLongR3 = new ModelRenderer(this, 27, 0);
        this.tentacleLongR3.setRotationPoint(0.0F, 0.0F, -9.7F);
        this.tentacleLongR3.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleLongR3, 0.0F, -0.22759093446006054F, 0.0F);
        this.tentacleLT4 = new ModelRenderer(this, 46, 0);
        this.tentacleLT4.setRotationPoint(0.0F, 0.0F, -6.7F);
        this.tentacleLT4.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.mantle = new ModelRenderer(this, 0, 0);
        this.mantle.setRotationPoint(0.0F, 0.0F, -1.0F);
        this.mantle.addBox(-4.0F, -4.0F, 0.0F, 8, 8, 11, 0.0F);
        this.setRotateAngle(mantle, -0.045553093477052F, 0.0F, 0.0F);
        this.tentacleT0 = new ModelRenderer(this, 46, 0);
        this.tentacleT0.setRotationPoint(0.0F, -2.4F, -6.7F);
        this.tentacleT0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.tentacleLM0 = new ModelRenderer(this, 46, 0);
        this.tentacleLM0.mirror = true;
        this.tentacleLM0.setRotationPoint(2.3F, 0.2F, -6.7F);
        this.tentacleLM0.addBox(-1.0F, -1.0F, -7.0F, 2, 2, 7, 0.0F);
        this.setRotateAngle(tentacleLM0, 0.0F, 0.0F, 1.5707963267948966F);
        this.tentacleLongL4.addChild(this.tentacleLongL5);
        this.tentacleRM1.addChild(this.tentacleRM2);
        this.tentacleLB2.addChild(this.tentacleLB3);
        this.tentacleRT2.addChild(this.tentacleRT3);
        this.tentacleLongR5.addChild(this.tentacleLongR6);
        this.mantle.addChild(this.mantleBack);
        this.tentacleLongL7.addChild(this.tentacleLongLHand);
        this.head.addChild(this.tentacleB0);
        this.head.addChild(this.tentacleRB0);
        this.tentacleRB2.addChild(this.tentacleRB3);
        this.mantleBack.addChild(this.mantleTop);
        this.head.addChild(this.beakLow);
        this.tentacleLB0.addChild(this.tentacleLB1);
        this.head.addChild(this.tentacleLB0);
        this.tentacleLongL1.addChild(this.tentacleLongL2);
        this.head.addChild(this.tentacleLongR0);
        this.head.addChild(this.tentacleLongL0);
        this.tentacleLT2.addChild(this.tentacleLT3);
        this.tentacleRM2.addChild(this.tentacleRM3);
        this.tentacleLB3.addChild(this.tentacleLB4);
        this.mantleTipTop.addChild(this.mantleTipLow);
        this.tentacleLongR0.addChild(this.tentacleLongR1);
        this.tentacleLM2.addChild(this.tentacleLM3);
        this.head.addChild(this.siphon);
        this.tentacleLongR3.addChild(this.tentacleLongR4);
        this.mantleTop.addChild(this.mantleTipTop);
        this.tentacleLongR1.addChild(this.tentacleLongR2);
        this.tentacleB3.addChild(this.tentacleB4);
        this.head.addChild(this.beakTop);
        this.head.addChild(this.lEye);
        this.tentacleT1.addChild(this.tentacleT2);
        this.head.addChild(this.tentacleRM0);
        this.tentacleRT3.addChild(this.tentacleRT4);
        this.tentacleRT0.addChild(this.tentacleRT1);
        this.tentacleRM0.addChild(this.tentacleRM1);
        this.tentacleLongR4.addChild(this.tentacleLongR5);
        this.tentacleLT1.addChild(this.tentacleLT2);
        this.tentacleT2.addChild(this.tentacleT3);
        this.tentacleRB0.addChild(this.tentacleRB1);
        this.tentacleLB1.addChild(this.tentacleLB2);
        this.tentacleLM1.addChild(this.tentacleLM2);
        this.mantleTipTop.addChild(this.fin0);
        this.tentacleLongL5.addChild(this.tentacleLongL6);
        this.tentacleB0.addChild(this.tentacleB1);
        this.tentacleLongR7.addChild(this.tentacleLongRHand);
        this.tentacleLongL3.addChild(this.tentacleLongL4);
        this.tentacleLM0.addChild(this.tentacleLM1);
        this.tentacleT3.addChild(this.tentacleT4);
        this.tentacleRM3.addChild(this.tentacleRM4);
        this.tentacleRB1.addChild(this.tentacleRB2);
        this.head.addChild(this.rEye);
        this.head.addChild(this.tentacleRT0);
        this.tentacleT0.addChild(this.tentacleT1);
        this.tentacleLongL6.addChild(this.tentacleLongL7);
        this.tentacleRT1.addChild(this.tentacleRT2);
        this.tentacleLongL0.addChild(this.tentacleLongL1);
        this.tentacleB1.addChild(this.tentacleB2);
        this.tentacleLM3.addChild(this.tentacleLM4);
        this.tentacleRB3.addChild(this.tentacleRB4);
        this.tentacleLongR6.addChild(this.tentacleLongR7);
        this.tentacleLongL2.addChild(this.tentacleLongL3);
        this.head.addChild(this.tentacleLT0);
        this.tentacleB2.addChild(this.tentacleB3);
        this.fin0.addChild(this.fin1);
        this.tentacleLT0.addChild(this.tentacleLT1);
        this.tentacleLongR2.addChild(this.tentacleLongR3);
        this.tentacleLT3.addChild(this.tentacleLT4);
        this.head.addChild(this.mantle);
        this.head.addChild(this.tentacleT0);
        this.head.addChild(this.tentacleLM0);
        this.mainTentacles = new ModelRenderer[] {
        tentacleLT0,
        tentacleRT0,
        tentacleT0,
        tentacleRM0,
        tentacleRB0,
        tentacleLM0,
        tentacleLB0,
        tentacleB0
        };
    }

    @Override
    public void render(MatrixStack matrixStackIn, IVertexBuilder bufferIn, int packedLightIn, int packedOverlayIn, float red, float green, float blue, float alpha) {
        this.head.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn);
    }

    @Override
    public void setRotationAngles(T entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.head.rotateAngleX = (float) (Math.PI / 2F);
        for(ModelRenderer m : mainTentacles) {
            m.rotateAngleX = -ageInTicks / 2F;
        }
    }

    public void setRotateAngle(ModelRenderer ModelRenderer, float x, float y, float z) {
        ModelRenderer.rotateAngleX = x;
        ModelRenderer.rotateAngleY = y;
        ModelRenderer.rotateAngleZ = z;
    }
}
